import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Store } from '../utils/store'


export default function Layout({title, children}) {

  const {state, dispatch} = useContext(Store)
  const {cart} = state
  const [cartItemsCount, setCartItemsCount]=useState(0)

  useEffect(()=> {
    setCartItemsCount(cart.cartItems.reduce((a, c )=> a+ c.quantity, 0)) //calcula cuantos items(PAGOS) se suman al carrito. Reduce recorre cada indice  apuntando a lo que le indique y retorna un nvo array
  
  }, [cart.cartItems])




  

  return (
   <div>
      <Head>
          <title>{title ? title + "- tienda" : "tienda"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

        <nav className="navbar navbar-expand-lg navbar-grey bg-grey">
          <div className="container-fluid">
              <Link href='/'>
                <a className='navbar-brand'>Navbar</a>
              </Link>
              <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
               <span className="navbar-toggler-icon" />
              </button>
             <div className="collapse navbar-collapse" id="navbarNav">
               <ul className="navbar-nav ms-auto">
                  <li className="nav-item">
                    <Link href="/cart">
                      <a className="nav-link active">Carrito<span className='text-white bg-danger rounded p-1'>{cartItemsCount}</span></a>
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          
        </nav>
      <main>
        {children}    
      </main>
   </div>

  )
}
